---
- name: configure java for unifi
  lineinfile:
    create: yes
    path: '{{ unifi_config_file }}'
    regexp: '^JAVA_HOME='
    line: 'JAVA_HOME={{ unifi_java_home }}'
  become: yes
  notify:
    - restart unifi

    
