---
#- name: install java packages
#  apt:
#    allow_unauthenticated: yes
#    name: "{{ unifi_java_packages }}"
#    state: "{{ unifi_packages_state }}"
#    update_cache: yes
#  become: yes
#  when: ansible_os_family == "Debian"
#  notify:
#    - restart unifi
- name: Add Oracle Java Repository
  become: yes
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Install Oracle Java 8
  become: yes
  apt: name={{item}} state=latest
  with_items:
    - oracle-java8-installer
    - ca-certificates
    - oracle-java8-set-default
    
- name: Accept Java 8 License
  become: yes
  debconf: name='oracle-java8-installer' question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
